---
- name: Troubleshoot and Fix WordPress Access
  hosts: ec2
  become: true
  tasks:
    - name: Check if WordPress directory exists
      stat:
        path: /var/www/html/wordpress
      register: wordpress_dir
      
    - name: Check WordPress directory content
      command: ls -la /var/www/html/wordpress
      register: wordpress_content
      ignore_errors: yes
      changed_when: false
      
    - name: Debug WordPress directory structure
      debug:
        msg: "{{ wordpress_content.stdout_lines }}"
      when: wordpress_dir.stat.exists
        
    - name: Check Apache configuration
      command: apachectl -t
      register: apache_config_check
      ignore_errors: yes
      changed_when: false
      
    - name: Display Apache virtual hosts
      command: apachectl -S
      register: apache_vhosts
      ignore_errors: yes
      changed_when: false
        
    - name: Debug Apache configuration
      debug:
        msg: 
          - "Config test result: {{ apache_config_check.stdout }}"
          - "Virtual hosts: {{ apache_vhosts.stdout_lines }}"
          
    - name: Ensure DocumentRoot exists
      file:
        path: /var/www/html/wordpress
        state: directory
        owner: apache
        group: apache
        mode: '0755'
        
    # Fix 1: Check if WordPress is extracted at the wrong location
    - name: Check if WordPress was extracted to wrong directory
      stat:
        path: /var/www/html/wordpress/wordpress
      register: nested_wordpress
      
    - name: Fix nested WordPress directory if it exists
      shell: mv /var/www/html/wordpress/wordpress/* /var/www/html/wordpress/ && rmdir /var/www/html/wordpress/wordpress
      when: nested_wordpress.stat.exists
      
    # Fix 2: Check if WordPress is in parent directory
    - name: Check if WordPress was extracted to parent directory
      stat:
        path: /var/www/html/index.php
      register: parent_wordpress
      
    - name: Fix WordPress in parent directory
      shell: rm -rf /var/www/html/wordpress && mkdir -p /var/www/html/wordpress && mv /var/www/html/*.php /var/www/html/wp-* /var/www/html/wordpress/
      when: parent_wordpress.stat.exists
      
    # Fix 3: Create a symbolic link
    - name: Create symbolic link from /wordpress to actual location
      file:
        src: /var/www/html/wordpress
        dest: /var/www/wordpress
        state: link
        
    # Fix 4: Update SELinux context
    - name: Set proper SELinux context
      shell: |
        semanage fcontext -a -t httpd_sys_content_t "/var/www/html/wordpress(/.*)?"
        semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/html/wordpress/wp-content(/.*)?"
        restorecon -Rv /var/www/html/wordpress
      ignore_errors: yes

    # Fix 5: Check and update Apache configuration
    - name: Ensure Apache default document root is updated
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^DocumentRoot.*'
        line: 'DocumentRoot "/var/www/html/wordpress"'
        
    - name: Ensure Directory directive is updated
      blockinfile:
        path: /etc/httpd/conf/httpd.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR WORDPRESS"
        block: |
          <Directory "/var/www/html/wordpress">
              AllowOverride All
              Require all granted
          </Directory>
        
    - name: Create .htaccess file for WordPress
      copy:
        dest: /var/www/html/wordpress/.htaccess
        content: |
          # BEGIN WordPress
          <IfModule mod_rewrite.c>
          RewriteEngine On
          RewriteBase /
          RewriteRule ^index\.php$ - [L]
          RewriteCond %{REQUEST_FILENAME} !-f
          RewriteCond %{REQUEST_FILENAME} !-d
          RewriteRule . /index.php [L]
          </IfModule>
          # END WordPress
        owner: apache
        group: apache
        mode: '0644'
        
    - name: Enable mod_rewrite
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^#LoadModule rewrite_module modules/mod_rewrite.so'
        line: 'LoadModule rewrite_module modules/mod_rewrite.so'
      
    - name: Restart Apache
      service:
        name: httpd
        state: restarted
