# Copied from ansible/woocommerce-deploy/woocommerce-playbook.yml
---
- name: Install and configure WooCommerce
  hosts: ec2
  become: yes
  vars:
    db_name: "{{ lookup('env', 'DB_NAME') }}"
    db_user: "{{ lookup('env', 'DB_USER') }}"
    db_password: "{{ lookup('env', 'DB_PASSWORD') }}"
    db_host: "{{ lookup('env', 'DB_HOST') }}"
  tasks:
    - name: Update package cache
      dnf:
        name: "*"
        state: latest
        
    - name: Install Apache, PHP 8.1+, MySQL client, and other required packages
      dnf:
        name: "{{ packages }}"
        state: present
      vars:
        packages:
          - httpd
          - php
          - php-mysqlnd
          - php-json
          - php-gd
          - php-mbstring
          - php-xml
          - php-intl
          - php-curl
          - php-zip
          - mariadb105
          - unzip
          - wget
          
    - name: Start and enable Apache
      service:
        name: httpd
        state: started
        enabled: yes
        
    - name: Create Apache virtual host configuration
      template:
        src: templates/wordpress.conf.j2
        dest: /etc/httpd/conf.d/wordpress.conf
      notify: Restart Apache
        
    - name: Download WordPress
      get_url:
        url: https://wordpress.org/latest.tar.gz
        dest: /tmp/wordpress.tar.gz
        
    - name: Create WordPress directory
      file:
        path: /var/www/html/wordpress
        state: directory
        owner: apache
        group: apache
        
    - name: Extract WordPress
      unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /var/www/html/
        remote_src: yes
        
    - name: Configure WordPress wp-config.php
      template:
        src: templates/wp-config.php.j2
        dest: /var/www/html/wordpress/wp-config.php
        owner: apache
        group: apache
        mode: '0640'
        
    - name: Install WooCommerce plugin
      shell: |
        wget https://downloads.wordpress.org/plugin/woocommerce.latest-stable.zip -P /tmp
        unzip /tmp/woocommerce.latest-stable.zip -d /var/www/html/wordpress/wp-content/plugins
      args:
        creates: /var/www/html/wordpress/wp-content/plugins/woocommerce
        
    - name: Set permissions
      file:
        path: /var/www/html/wordpress
        owner: apache
        group: apache
        recurse: yes
        mode: 'u=rwX,g=rX,o=rX'
        
    - name: Configure SELinux for WordPress (if enabled)
      shell: |
        semanage fcontext -a -t httpd_sys_rw_content_t "/var/www/html/wordpress(/.*)?"
        restorecon -Rv /var/www/html/wordpress
      ignore_errors: yes
      
  handlers:
    - name: Restart Apache
      service:
        name: httpd
        state: restarted
